security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login
    
    firewalls:
        main:
            provider: app_user_provider
            custom_authenticator: Iepg\Bundle\Cas\Controller\CasAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cas-connection/cas-admin, roles: ROLE_ADMIN }
        - { path: ^/cas-connection/cas-user, roles: ROLE_USER }